### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by shonfeder**
Adds an MIT license, as per Tarides's policy.

If any contributors feel that they should be included in the copy right notice explicitly,
please add yourself, in this PR or in a followup!

### CODE REVIEW

**Review by punchagan — APPROVED** [review]

**Comment by shonfeder** [comment]
Hi, @dinosaure :) Are you OK with us fixing the oversight of an omitted license here by adding the MIT license?

**Comment by dinosaure** [comment]
It's ok for me :+1: .

**Comment by shonfeder** [comment]
Great. Thanks! Ah, I see I also need an OK from @hannesm. Are you OK with us adding an MIT licenses here?

**Comment by hannesm** [comment]
sure, thanks for taking care of adding licenses.

**Comment by shonfeder** [comment]
Thanks and thanks for the thanks :)

**Pull request merged**
